#use_frameworks!
source 'http://192.168.10.81/IOS/commline/iOSPod.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'runtimeDemo_Example' do
  pod 'runtimeDemo', :path => '../'

  target 'runtimeDemo_Tests' do
    inherit! :search_paths

    
  end
end
